name: npm-publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-npm:
    runs-on: self-hosted
    steps:
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            npm-token:nitraai/npm-token

      - uses: actions/checkout@v3

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ steps.secrets.outputs.npm-token }}
          access: public
          check-version: true
          package: ./npm/package.json

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          # from-tag: 'current tag'
          to-tag: HEAD
          allow-unknown: true
